"""Add more info to User model

Revision ID: 5563f8a45c1c
Revises: 9bee6156e4b2
Create Date: 2018-10-21 15:08:31.238363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5563f8a45c1c'
down_revision = '9bee6156e4b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
